// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"whoam.xyz/ent/migrate"

	"whoam.xyz/ent/ras"

	"github.com/facebook/ent/dialect"
	"github.com/facebook/ent/dialect/sql"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// RAS is the client for interacting with the RAS builders.
	RAS *RASClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.RAS = NewRASClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		RAS:    NewRASClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(*sql.Driver).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: &txDriver{tx: tx, drv: c.driver}, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		config: cfg,
		RAS:    NewRASClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		RAS.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.RAS.Use(hooks...)
}

// RASClient is a client for the RAS schema.
type RASClient struct {
	config
}

// NewRASClient returns a client for the RAS from the given config.
func NewRASClient(c config) *RASClient {
	return &RASClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ras.Hooks(f(g(h())))`.
func (c *RASClient) Use(hooks ...Hook) {
	c.hooks.RAS = append(c.hooks.RAS, hooks...)
}

// Create returns a create builder for RAS.
func (c *RASClient) Create() *RASCreate {
	mutation := newRASMutation(c.config, OpCreate)
	return &RASCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RAS entities.
func (c *RASClient) CreateBulk(builders ...*RASCreate) *RASCreateBulk {
	return &RASCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RAS.
func (c *RASClient) Update() *RASUpdate {
	mutation := newRASMutation(c.config, OpUpdate)
	return &RASUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RASClient) UpdateOne(r *RAS) *RASUpdateOne {
	mutation := newRASMutation(c.config, OpUpdateOne, withRAS(r))
	return &RASUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RASClient) UpdateOneID(id uuid.UUID) *RASUpdateOne {
	mutation := newRASMutation(c.config, OpUpdateOne, withRASID(id))
	return &RASUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RAS.
func (c *RASClient) Delete() *RASDelete {
	mutation := newRASMutation(c.config, OpDelete)
	return &RASDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *RASClient) DeleteOne(r *RAS) *RASDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *RASClient) DeleteOneID(id uuid.UUID) *RASDeleteOne {
	builder := c.Delete().Where(ras.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RASDeleteOne{builder}
}

// Query returns a query builder for RAS.
func (c *RASClient) Query() *RASQuery {
	return &RASQuery{config: c.config}
}

// Get returns a RAS entity by its id.
func (c *RASClient) Get(ctx context.Context, id uuid.UUID) (*RAS, error) {
	return c.Query().Where(ras.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RASClient) GetX(ctx context.Context, id uuid.UUID) *RAS {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RASClient) Hooks() []Hook {
	return c.hooks.RAS
}
