// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"whoam.xyz/ent/method"
	"whoam.xyz/ent/service"
)

// MethodCreate is the builder for creating a Method entity.
type MethodCreate struct {
	config
	mutation *MethodMutation
	hooks    []Hook
}

// SetName sets the name field.
func (mc *MethodCreate) SetName(s string) *MethodCreate {
	mc.mutation.SetName(s)
	return mc
}

// SetRoute sets the route field.
func (mc *MethodCreate) SetRoute(s string) *MethodCreate {
	mc.mutation.SetRoute(s)
	return mc
}

// SetScope sets the scope field.
func (mc *MethodCreate) SetScope(m method.Scope) *MethodCreate {
	mc.mutation.SetScope(m)
	return mc
}

// SetNillableScope sets the scope field if the given value is not nil.
func (mc *MethodCreate) SetNillableScope(m *method.Scope) *MethodCreate {
	if m != nil {
		mc.SetScope(*m)
	}
	return mc
}

// SetOwnerID sets the owner edge to Service by id.
func (mc *MethodCreate) SetOwnerID(id int) *MethodCreate {
	mc.mutation.SetOwnerID(id)
	return mc
}

// SetOwner sets the owner edge to Service.
func (mc *MethodCreate) SetOwner(s *Service) *MethodCreate {
	return mc.SetOwnerID(s.ID)
}

// Mutation returns the MethodMutation object of the builder.
func (mc *MethodCreate) Mutation() *MethodMutation {
	return mc.mutation
}

// Save creates the Method in the database.
func (mc *MethodCreate) Save(ctx context.Context) (*Method, error) {
	var (
		err  error
		node *Method
	)
	mc.defaults()
	if len(mc.hooks) == 0 {
		if err = mc.check(); err != nil {
			return nil, err
		}
		node, err = mc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MethodMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mc.check(); err != nil {
				return nil, err
			}
			mc.mutation = mutation
			node, err = mc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(mc.hooks) - 1; i >= 0; i-- {
			mut = mc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MethodCreate) SaveX(ctx context.Context) *Method {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (mc *MethodCreate) defaults() {
	if _, ok := mc.mutation.Scope(); !ok {
		v := method.DefaultScope
		mc.mutation.SetScope(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MethodCreate) check() error {
	if _, ok := mc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if _, ok := mc.mutation.Route(); !ok {
		return &ValidationError{Name: "route", err: errors.New("ent: missing required field \"route\"")}
	}
	if _, ok := mc.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New("ent: missing required field \"scope\"")}
	}
	if v, ok := mc.mutation.Scope(); ok {
		if err := method.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf("ent: validator failed for field \"scope\": %w", err)}
		}
	}
	if _, ok := mc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner", err: errors.New("ent: missing required edge \"owner\"")}
	}
	return nil
}

func (mc *MethodCreate) sqlSave(ctx context.Context) (*Method, error) {
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (mc *MethodCreate) createSpec() (*Method, *sqlgraph.CreateSpec) {
	var (
		_node = &Method{config: mc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: method.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: method.FieldID,
			},
		}
	)
	if value, ok := mc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: method.FieldName,
		})
		_node.Name = value
	}
	if value, ok := mc.mutation.Route(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: method.FieldRoute,
		})
		_node.Route = value
	}
	if value, ok := mc.mutation.Scope(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: method.FieldScope,
		})
		_node.Scope = value
	}
	if nodes := mc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   method.OwnerTable,
			Columns: []string{method.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: service.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MethodCreateBulk is the builder for creating a bulk of Method entities.
type MethodCreateBulk struct {
	config
	builders []*MethodCreate
}

// Save creates the Method entities in the database.
func (mcb *MethodCreateBulk) Save(ctx context.Context) ([]*Method, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Method, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MethodMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (mcb *MethodCreateBulk) SaveX(ctx context.Context) []*Method {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
