// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"net/url"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"whoam.xyz/ent/predicate"
	"whoam.xyz/ent/ras"
	"whoam.xyz/ent/user"
)

// RASUpdate is the builder for updating RAS entities.
type RASUpdate struct {
	config
	hooks    []Hook
	mutation *RASMutation
}

// Where adds a new predicate for the builder.
func (ru *RASUpdate) Where(ps ...predicate.RAS) *RASUpdate {
	ru.mutation.predicates = append(ru.mutation.predicates, ps...)
	return ru
}

// SetSubject sets the subject field.
func (ru *RASUpdate) SetSubject(s string) *RASUpdate {
	ru.mutation.SetSubject(s)
	return ru
}

// SetPostURI sets the post_uri field.
func (ru *RASUpdate) SetPostURI(u *url.URL) *RASUpdate {
	ru.mutation.SetPostURI(u)
	return ru
}

// SetRedirectURI sets the redirect_uri field.
func (ru *RASUpdate) SetRedirectURI(u *url.URL) *RASUpdate {
	ru.mutation.SetRedirectURI(u)
	return ru
}

// SetState sets the state field.
func (ru *RASUpdate) SetState(r ras.State) *RASUpdate {
	ru.mutation.SetState(r)
	return ru
}

// SetOrganizerID sets the organizer edge to User by id.
func (ru *RASUpdate) SetOrganizerID(id int) *RASUpdate {
	ru.mutation.SetOrganizerID(id)
	return ru
}

// SetNillableOrganizerID sets the organizer edge to User by id if the given value is not nil.
func (ru *RASUpdate) SetNillableOrganizerID(id *int) *RASUpdate {
	if id != nil {
		ru = ru.SetOrganizerID(*id)
	}
	return ru
}

// SetOrganizer sets the organizer edge to User.
func (ru *RASUpdate) SetOrganizer(u *User) *RASUpdate {
	return ru.SetOrganizerID(u.ID)
}

// Mutation returns the RASMutation object of the builder.
func (ru *RASUpdate) Mutation() *RASMutation {
	return ru.mutation
}

// ClearOrganizer clears the "organizer" edge to type User.
func (ru *RASUpdate) ClearOrganizer() *RASUpdate {
	ru.mutation.ClearOrganizer()
	return ru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RASUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ru.hooks) == 0 {
		if err = ru.check(); err != nil {
			return 0, err
		}
		affected, err = ru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RASMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ru.check(); err != nil {
				return 0, err
			}
			ru.mutation = mutation
			affected, err = ru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ru.hooks) - 1; i >= 0; i-- {
			mut = ru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RASUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RASUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RASUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *RASUpdate) check() error {
	if v, ok := ru.mutation.State(); ok {
		if err := ras.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf("ent: validator failed for field \"state\": %w", err)}
		}
	}
	return nil
}

func (ru *RASUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   ras.Table,
			Columns: ras.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: ras.FieldID,
			},
		},
	}
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Subject(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: ras.FieldSubject,
		})
	}
	if value, ok := ru.mutation.PostURI(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: ras.FieldPostURI,
		})
	}
	if value, ok := ru.mutation.RedirectURI(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: ras.FieldRedirectURI,
		})
	}
	if value, ok := ru.mutation.State(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: ras.FieldState,
		})
	}
	if ru.mutation.OrganizerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ras.OrganizerTable,
			Columns: []string{ras.OrganizerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.OrganizerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ras.OrganizerTable,
			Columns: []string{ras.OrganizerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ras.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// RASUpdateOne is the builder for updating a single RAS entity.
type RASUpdateOne struct {
	config
	hooks    []Hook
	mutation *RASMutation
}

// SetSubject sets the subject field.
func (ruo *RASUpdateOne) SetSubject(s string) *RASUpdateOne {
	ruo.mutation.SetSubject(s)
	return ruo
}

// SetPostURI sets the post_uri field.
func (ruo *RASUpdateOne) SetPostURI(u *url.URL) *RASUpdateOne {
	ruo.mutation.SetPostURI(u)
	return ruo
}

// SetRedirectURI sets the redirect_uri field.
func (ruo *RASUpdateOne) SetRedirectURI(u *url.URL) *RASUpdateOne {
	ruo.mutation.SetRedirectURI(u)
	return ruo
}

// SetState sets the state field.
func (ruo *RASUpdateOne) SetState(r ras.State) *RASUpdateOne {
	ruo.mutation.SetState(r)
	return ruo
}

// SetOrganizerID sets the organizer edge to User by id.
func (ruo *RASUpdateOne) SetOrganizerID(id int) *RASUpdateOne {
	ruo.mutation.SetOrganizerID(id)
	return ruo
}

// SetNillableOrganizerID sets the organizer edge to User by id if the given value is not nil.
func (ruo *RASUpdateOne) SetNillableOrganizerID(id *int) *RASUpdateOne {
	if id != nil {
		ruo = ruo.SetOrganizerID(*id)
	}
	return ruo
}

// SetOrganizer sets the organizer edge to User.
func (ruo *RASUpdateOne) SetOrganizer(u *User) *RASUpdateOne {
	return ruo.SetOrganizerID(u.ID)
}

// Mutation returns the RASMutation object of the builder.
func (ruo *RASUpdateOne) Mutation() *RASMutation {
	return ruo.mutation
}

// ClearOrganizer clears the "organizer" edge to type User.
func (ruo *RASUpdateOne) ClearOrganizer() *RASUpdateOne {
	ruo.mutation.ClearOrganizer()
	return ruo
}

// Save executes the query and returns the updated entity.
func (ruo *RASUpdateOne) Save(ctx context.Context) (*RAS, error) {
	var (
		err  error
		node *RAS
	)
	if len(ruo.hooks) == 0 {
		if err = ruo.check(); err != nil {
			return nil, err
		}
		node, err = ruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RASMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ruo.check(); err != nil {
				return nil, err
			}
			ruo.mutation = mutation
			node, err = ruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ruo.hooks) - 1; i >= 0; i-- {
			mut = ruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RASUpdateOne) SaveX(ctx context.Context) *RAS {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RASUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RASUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *RASUpdateOne) check() error {
	if v, ok := ruo.mutation.State(); ok {
		if err := ras.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf("ent: validator failed for field \"state\": %w", err)}
		}
	}
	return nil
}

func (ruo *RASUpdateOne) sqlSave(ctx context.Context) (_node *RAS, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   ras.Table,
			Columns: ras.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: ras.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing RAS.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := ruo.mutation.Subject(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: ras.FieldSubject,
		})
	}
	if value, ok := ruo.mutation.PostURI(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: ras.FieldPostURI,
		})
	}
	if value, ok := ruo.mutation.RedirectURI(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: ras.FieldRedirectURI,
		})
	}
	if value, ok := ruo.mutation.State(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: ras.FieldState,
		})
	}
	if ruo.mutation.OrganizerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ras.OrganizerTable,
			Columns: []string{ras.OrganizerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.OrganizerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ras.OrganizerTable,
			Columns: []string{ras.OrganizerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RAS{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues()
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ras.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
