// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"whoam.xyz/ent/ras"
	"whoam.xyz/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	rasFields := schema.RAS{}.Fields()
	_ = rasFields
	// rasDescCreatedAt is the schema descriptor for created_at field.
	rasDescCreatedAt := rasFields[5].Descriptor()
	// ras.DefaultCreatedAt holds the default value on creation for the created_at field.
	ras.DefaultCreatedAt = rasDescCreatedAt.Default.(func() time.Time)
	// rasDescID is the schema descriptor for id field.
	rasDescID := rasFields[0].Descriptor()
	// ras.DefaultID holds the default value on creation for the id field.
	ras.DefaultID = rasDescID.Default.(func() uuid.UUID)
}
