// Code generated by entc, DO NOT EDIT.

package service

const (
	// Label holds the string label denoting the service type in the database.
	Label = "service"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldDomain holds the string denoting the domain field in the database.
	FieldDomain = "domain"
	// FieldCloneURI holds the string denoting the clone_uri field in the database.
	FieldCloneURI = "clone_uri"

	// EdgeMethods holds the string denoting the methods edge name in mutations.
	EdgeMethods = "methods"

	// Table holds the table name of the service in the database.
	Table = "services"
	// MethodsTable is the table the holds the methods relation/edge.
	MethodsTable = "methods"
	// MethodsInverseTable is the table name for the Method entity.
	// It exists in this package in order to avoid circular dependency with the "method" package.
	MethodsInverseTable = "methods"
	// MethodsColumn is the table column denoting the methods relation/edge.
	MethodsColumn = "service_methods"
)

// Columns holds all SQL columns for service fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSubject,
	FieldDomain,
	FieldCloneURI,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	DomainValidator func(string) error
	// CloneURIValidator is a validator for the "clone_uri" field. It is called by the builders before save.
	CloneURIValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)
